title: Abhisek Chowdhury
url: "https://yuviabhi.github.io"
baseurl: "/researcher"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/yuviabhi"
footer_text: "2020 &copy; Abhisek Chowdhury"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/researcher/"
 - name: "Resume"
   link: "Abhisek_CV.pdf"
 - name: "Showcase"
   link: "works"
 - name: "Contact"
   link: "contact"
 
